### ISSUE TITLE
Vectorize search?

### ISSUE THREAD

**Issue by endrebak** [kylessmith/ailist#1]
Great work. 

I'd like to time this library against my NCLS. Would you consider adding a way to vectorize search too? So that you could query with numpy arrays. 

If you decide to do this you should look into the decorators

```
@cython.boundscheck(False)
@cython.wraparound(False)
@cython.initializedcheck(False)
```

**Comment by kylessmith** [comment]
Thanks!

I have implemented a vectorized search in the `.intersect_from_array()` method. I also updated the README file with a use example. Hopefully, this is what you were looking for. I have not done extensive benchmarking, but it seems to yield the same results as your `.all_overlaps_both()` method. The returned indices are in a different order though.

**Comment by endrebak** [comment]
Thanks, I'll look into it later when I have the time :)

Without the `intersect_from_array` your code was likely a lot slower because doing loops and function calls in Python is much slower than in C. Now it will be interesting to compare the two.

And yes, the NCLS has sort order guarantees so if you need the results to be sorted the NCLS is likely the better choice because sorting is an expensive operation :)

**Comment by endrebak** [comment]
When you feel the library has been vetted enough, you might want to make a post about it on biostars. I'm sure other people would be interested.

**Comment by endrebak** [comment]
According to one benchmark, the AIList is 10 times as fast to build, but half as slow for search.

Feel free to play around with this to further optimize your library:

```
import mkl
mkl.set_num_threads(1)

import pyranges as pr

size = int(1e6)

import numpy as np

np.random.seed(0)

c = pr.data.chromsizes()
c1 = c.head(1)

a = pr.random(size, strand=False, chromsizes=c1, int64=True).df.drop("Chromosome", 1).to_numpy()
a2 = pr.random(size, strand=False, chromsizes=c1, int64=True).df.drop("Chromosome", 1).to_numpy()

values = np.ones(size)
ix = np.arange(size, dtype=np.int64)

from ailist import AIList
i = AIList()

%time i.from_array(a[:, 0], a[:, 1], ix, values)
# Wall time: 17.1 ms

%time ai_res = i.intersect_from_array(a2[:, 0], a2[:, 1], ix)
# Wall time: 613 ms

len(ai_res)
# 797600

from ncls import NCLS

%time n = NCLS(a[:, 0], a[:, 1], ix)
# Wall time: 195 ms

%time n_res = n.all_overlaps_both(a2[:, 0], a2[:, 1], ix)
# Wall time: 343 ms
```

This seems to hold true for `size = int(1e7)` too. 

Please tell me if you are able to make AIList consistently faster for searches too :)

**Comment by endrebak** [comment]
I've had a look at your code and it looks really nice. I could not find anything you have done that should slow searches down. 

I do not know how familiar you are with cython, but it has an annotate option:
`cython -a yourfile.pyx` creates a html file that shows you places in your code that are potentially slow (lots of Python interop) :)

**Comment by endrebak** [comment]
Also, I met @nsheff at genome informatics. He was really nice. He was busy with writing some applications now, but was intending to get back to us about implementing and maintaining the AIList for Python :) I should fork you library and take a stab at it myself to see if I can get it back to C speed :)

Edit:

It is the function query_from_array that takes the brunt of the time:

```
import time
start = time()
cdef ailist_t *total_overlaps = ailist_query_from_array(self.interval_list, &starts[0], &ends[0], &indices[0], length)
end = time()
print("timing query_from_array:", end - start)
# 0.5120000839233398
```

I do not know any good tools for benchmarking at the C level. I'm hoping there is one obvious bottleneck we can fix to get massive speedups :)

**Comment by endrebak** [comment]
It seems that the benchmarks read beds and query at the same time. They do not query using in-memory arrays like we do. 

Untested hypothesis: Perhaps the NCList is faster when rapidly iterating over queries which are all in memory?

**Comment by kylessmith** [comment]
Thanks for looking into this! I will have to checkout the annotation option in Cython. It sounds like genome informatics is a pretty good conference if you were both there, I will have to check that out as well. I agree that the benchmarking appears to have some nuance and might be very different for rapidly iterating over queries in memory vs. many individual queries.

I ran your benchmarking code with one change. I called the construction of the AIList before querying. This would explain why the construction times were so different. I ran this on my MacBook Pro initiating an environment: 
```
conda create -n ailist_test python pyranges cython ipython
conda activate ailist_test
pip install ailist

```

Then I ran the benchmarking code:

```
import mkl
mkl.set_num_threads(1)

import pyranges as pr

size = int(1e6)

import numpy as np

np.random.seed(0)

c = pr.data.chromsizes()
c1 = c.head(1)

a = pr.random(size, strand=False, chromsizes=c1, int64=True).df.drop("Chromosome", 1).to_numpy()
a2 = pr.random(size, strand=False, chromsizes=c1, int64=True).df.drop("Chromosome", 1).to_numpy()

values = np.ones(size)
ix = np.arange(size, dtype=np.int64)

from ailist import AIList
i = AIList()

%time i.from_array(a[:, 0], a[:, 1], ix, values)
#CPU times: user 8.68 ms, sys: 5.69 ms, total: 14.4 ms
#Wall time: 14.4 ms

%time i.construct()
#CPU times: user 150 ms, sys: 21.3 ms, total: 171 ms
#Wall time: 172 ms

%time ai_res = i.intersect_from_array(a2[:, 0], a2[:, 1], ix)
#CPU times: user 469 ms, sys: 18.1 ms, total: 487 ms
#Wall time: 486 ms

from ncls import NCLS

%time n = NCLS(a[:, 0], a[:, 1], ix)
#CPU times: user 209 ms, sys: 8.93 ms, total: 218 ms
#Wall time: 219 ms

%time n_res = n.all_overlaps_both(a2[:, 0], a2[:, 1], ix)
#CPU times: user 621 ms, sys: 3.47 ms, total: 625 ms
#Wall time: 625 ms
```

Run in this way the times seem to be pretty competitive. When I run the queries on my desktop the timings seem even closer: 308ms (ailist) and 330ms (ncls). Not sure what to make of that.

**Comment by endrebak** [comment]
Cool! I had misunderstood the API slightly.

So for the whole comparision the AIList now takes 672 ms, while the NCLS now takes 844 ms.  

For 1e7:

```
AIList: 0.2 + 2.41 + 11.1
           13.71

NCLS: 12.2 + 3.91
            16.11

AIList: 13.71
NCLS: 16.11
```

This is nice, but means that the NCLS only takes 15% more time. Since the NCLS has sort-order guarantees which I need for pyranges  (and which is expensive to compute) I have to stick to the NCLS. If @jf2016GH or @aakrosh could help us get to the 5x-18x speedup claimed [here](http://ailist.databio.org/en/latest/) I would consider switching :)

**Comment by kylessmith** [comment]
Ya, that speedup could be due to the difference in how chromosomes labels were handled in the original c distribution.

**Comment by jf2016GH** [comment]
Thanks for your interest in AIList. 
For flat and near-flat interval datasets, this is expected. Read the paper and its updates to get a better understanding.

    On Friday, November 8, 2019, 12:46:07 PM EST, Endre Bakken Stovner <notifications@github.com> wrote:  
 
 
Cool! I had misunderstood the API slightly.

So for the whole comparision the AIList now takes 672 ms, while the NCLS now takes 844 ms.

For 1e7:
AIList: 0.2 + 2.41 + 11.1
           13.71

NCLS: 12.2 + 3.91
            16.11

AIList: 13.71
NCLS: 16.11

This is nice, but means that the NCLS only takes 15% more time. Since the NCLS has sort-order guarantees which I need for pyranges (and which is expensive to compute) I have to stick to the NCLS. If @jf2016GH or @aakrosh could help us get to the claimed 5x-18x speedup I would consider switching :)

**Comment by nsheff** [comment]
Just to chime in -- what @jf2016GH is referring to is that where AIList really shines is when there are overlaps in the interval sets. For an interval set with no overlaps,  there is a single sort order, and then in fact you could just use a binary search and you don't even need an NCList, because there should be no nesting needed as there is no containment. In that case these structures collapse into a basic list, really.

Therefore, your decision to use an NCList means you're interested in interval sets with potential overlaps, right? In that case, you should also benchmark datasets that have overlapping and containing intervals, and that's where you will see the improvements from AIList.

I'd like to understand more about the sort-order guarantees you require. I don't quite understand what you mean by this and I don't see why AIList wouldn't provide it...

**Comment by endrebak** [comment]
Here are my benchmarks using your data on my macbook pro with 16gigs of ram:

```
------------------------------
Subject file: chainOrnAna1.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.37735605239868164
Querying NCLS took 92.85288500785828
Building ai took 0.3491032123565674
Querying ai took 75.86743712425232
------------------------------
Subject file: chainVicPac2.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.39214491844177246
Querying NCLS took 92.57744908332825
Building ai took 0.3954188823699951
Querying ai took 73.98339509963989
------------------------------
Subject file: chainXenTro3Link.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.3832888603210449
Querying NCLS took 33.25918006896973
Building ai took 0.25615978240966797
Querying ai took 27.772515296936035
------------------------------
Subject file: chainMonDom5Link.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.26062488555908203
Querying NCLS took 10.006813049316406
Building ai took 0.20964312553405762
Querying ai took 4.56371283531189
```

It seems like the best speedup is 2 times for the last comparison. Most are only 20% better for the ailist. I will try again on a 200GB server and use the whole datasets. In the above I only used 1.5 million rows since I was using my laptop. 

This is nice, but it seems that when comparing a library of reads against a genocde annotation for example there is not going to be that much difference between the two.

My benchmark: https://gist.github.com/endrebak/615082362b7a392c74daca0cad760e8d

**Comment by endrebak** [comment]
This is the mem use (in maxRSS) I get from a naive use of `/usr/bin/time -v` on my script:

```
# 1 AI:   9744720
# 1 NC: 9513088

# 1.5 AI: 12219348
# 1.5 NC: 11530360
```

Since the DataFrames are the same size for each run the difference must be due to the algorithms. There seems to be an insignificant advantage in favor of the NCLS.

Note that all of these benchmarks are for in-memory data, while your benchmarks streamed at least one of the files IIRC.

**Comment by jf2016GH** [comment]
I assume that these results are from your python wrappers of AIList and NCList; if so, then I am glad to see it.
Take a look at the update of AIList: the c code runs 30x faster than your benchmarks.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
databio/AIList

Augmented interval list (AIList): a novel data structure for efficient genomic interval search - databio/AIList
 |

 |

 |





Thank you for your effort to wrap the AIList.

    On Saturday, November 9, 2019, 6:27:10 PM EST, Endre Bakken Stovner <notifications@github.com> wrote:  
 
 
Here are my benchmarks using your data on my macbook pro with 16gigs of ram:
------------------------------
Subject file: chainOrnAna1.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.37735605239868164
Querying NCLS took 92.85288500785828
Building ai took 0.3491032123565674
Querying ai took 75.86743712425232
------------------------------
Subject file: chainVicPac2.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.39214491844177246
Querying NCLS took 92.57744908332825
Building ai took 0.3954188823699951
Querying ai took 73.98339509963989
------------------------------
Subject file: chainXenTro3Link.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.3832888603210449
Querying NCLS took 33.25918006896973
Building ai took 0.25615978240966797
Querying ai took 27.772515296936035
------------------------------
Subject file: chainMonDom5Link.bed (1.5), Query file: chainRn4.bed (1.5)
Building NCLS took 0.26062488555908203
Querying NCLS took 10.006813049316406
Building ai took 0.20964312553405762
Querying ai took 4.56371283531189

It seems like the best speedup is 2 times for the last comparison. Most are only 20% better for the ailist. I will try again on a 200GB server and use the whole datasets. In the above I only used 1.5 million rows since I was using my laptop.

This is nice, but it seems that when comparing a library of reads against a genocde annotation for example there is not going to be that much difference between the two.

My benchmark: https://gist.github.com/endrebak/615082362b7a392c74daca0cad760e8d

**Comment by nsheff** [comment]
That's great, thanks @endrebak for doing that. @jf2016GH, there's [a link there](https://gist.github.com/endrebak/615082362b7a392c74daca0cad760e8d) to the code used to run the benchmarks -- which are indeed in python. you can see exactly how they were generated.

> Note that all of these benchmarks are for in-memory data, 

As you hint, I think the main thing is probably the difference of using in-memory. If I remember right a lot of the AIList improvement was due to data loading. Here, you're not considering that because you're reading the data into memory in python and then using that to construct the data structures. @jf2016GH can you comment further?  We will need to look into this further. Could we provide a smarter way to load the data directly into the AIList structure rather than reading it in with `read_csv` like [this](https://gist.github.com/endrebak/615082362b7a392c74daca0cad760e8d#file-compare_ai_and_ncls-py-L48) ?

Two other points:
- besides the loading question above, which I think is the biggest point, there may be other python overhead issues that would dilute the pure C results
- is the implementation of nclist different from the one we used? I think @jf2016GH grabbed the original, and yours may have some optimizations?

**Comment by endrebak** [comment]
I did not mean to sound negative, so far the AIList is an improvement - I have not found any cases where it is slower. And for some cases, like the last files benchmarked above I suspect the AIList is going to be even faster when we increase the size to e.g. 10 million instead of 1 million.

I tested an alternative Cython version in the link below. My idea was to build the array of results directly instead of 1) adding the results to an ailist and then 2) putting the results in an array afterwards like @kylessmith is doing. My version is actually slower though, beats me why. It is not due to Python interop - I checked. https://gist.github.com/endrebak/d11b65079ac5aba8e6ca44b8f3613ca2

My optimizations:

I have made a 32-bit version of the NCLS, but did not use those in the benchmark. I have also reduced the size of each interval in the NCLS from five ints to three, but that should not matter that much except a 40% mem reduction. There were lots of things I did to chip off speed, but none that I remember.

My guess is that my NCLS achieves great memory locality which is typically much more important than algorithmic runtime on modern machines. But I'd love to understand this better so I will follow any developments :)

**Comment by jf2016GH** [comment]
The time cost for read_csv(..) was not recorded.  Also all tests for AIList benchmarks used in-memory data. I'll test the python code of  @endrebak sometime next week on my laptop.


    On Saturday, November 9, 2019, 7:45:32 PM EST, Nathan Sheffield <notifications@github.com> wrote:  
 
 
That's great, thanks @endrebak for doing that. @jf2016GH, there's a link there to the code used to run the benchmarks -- which are indeed in python. you can see exactly how they were generated.


Note that all of these benchmarks are for in-memory data,


As you hint, I think the main thing is probably the difference of using in-memory. If I remember right a lot of the AIList improvement was due to data loading. Here, you're not considering that because you're reading the data into memory in python and then using that to construct the data structures. @jf2016GH can you comment further? We will need to look into this further. Could we provide a smarter way to load the data directly into the AIList structure rather than reading it in with read_csv like this ?

Two other points:
   
   - besides the loading question above, which I think is the biggest point, there may be other python overhead issues that would dilute the pure C results
   - is the implementation of nclist different from the one we used? I think @jf2016GH grabbed the original, and yours may have some optimizations?

**Comment by endrebak** [comment]
But the CSV is read _once_ and not included in the timings for either the NCLS or AIList as I am using the @kylessmith AIList version which also uses the in-memory array.

**Comment by endrebak** [comment]
Here you see his version of the algorithm which uses in-memory arrays for querying: https://github.com/kylessmith/ailist/blob/master/ailist/ailist.pyx#L535

There is no Python interop overhead to speak of. I checked with `cython -a ailist.pyx && open ailist.html`.

Now I remember a weird behavior I found which I tried to fix with my version above.

With these timings added to the code:
  
```
@cython.boundscheck(False)
@cython.wraparound(False)
@cython.initializedcheck(False)
cdef long[:,::1] _intersect_from_array(AIList self, const long[::1] starts, const long[::1] ends, const long[::1] indices):
    cdef int length = len(starts)
    start = time()
    cdef ailist_t *total_overlaps = ailist_query_from_array(self.interval_list, &starts[0], &ends[0], &indices[0], length)
    end = time()
    print("timing query_from_array:", end - start)

    cdef long[:,::1] results = np.zeros((2,total_overlaps.nr), dtype=np.long)

    start = time()
    cdef int i
    for i in range(total_overlaps.nr):
        results[0, i] = <int>total_overlaps.interval_list[i].value
        results[1, i] = total_overlaps.interval_list[i].index
    end = time()

    print("timing fetch results:", end - start)

    start = time()
    ailist_destroy(total_overlaps)
    end = time()

    print("timing ailist destroy:", end - start)

    #return np.asarray(results)
    return results

```

You see somethIng like this running on large datasets:

```
timing query_from_array: 10.008397102355957
timing fetch results: 21.556501865386963
timing ailist destroy: 0.9231340885162354
```

But the lines that take a lot of time https://github.com/kylessmith/ailist/blob/master/ailist/ailist.pyx#L545-547
are without Python overhead. Might it be that fetching the data from the AIList after finding the intersection is slow?

Anyways, if you are able to fix this one last thing and have a ten second runtime instead of 31, you would have something people (including me) would bother to switch to :)

**Comment by endrebak** [comment]
I started looking into the slow fetching of the results mentioned in the previous post. I found out it was due to using swap disk space since the data was too big for memory. Sorry. It seems like the Cython version here is pretty much optimal :)

**Comment by nsheff** [comment]
> I started looking into the slow fetching of the results mentioned in the previous post. I found out it was due to using swap disk space since the data was too big for memory. Sorry. It seems like the Cython version here is pretty much optimal :)

Can you clarify? With your revisions did the benchmarks match what we were originally proposing better? Can you share the new timings?

**Comment by endrebak** [comment]
The timing comparisons of NCLS against AIList that I posted has not changed, but yesterday I made a comment about of how parts of Kyle's implementation took a weirdly long time. That part was due to me doing the benchmarks incorrectly.

**Comment by kylessmith** [comment]
I have pushed an update to the `intersect_from_array` method. It should be more efficient in terms of both run time and memory usage. Using the original benchmark code with `size = int(1e7)` it might take ~%67 of the time that ncls takes: AIList: `CPU times: user 8.07 s, sys: 952 ms, total: 9.02 s; Wall time: 9.04 s`; ncls: `CPU times: user 11.9 s, sys: 1.27 s, total: 13.2 s; Wall time: 13.5 s`; The memory usage is improved as well (no duplication of data).

**Comment by kylessmith** [comment]
These updates have been pushed to the github but not the pip version yet.

**Comment by jf2016GH** [comment]
Thanks. 

    On Wednesday, November 13, 2019, 1:21:07 PM EST, Kyle Smith <notifications@github.com> wrote:  
 
 
I have pushed an update to the intersect_from_array method. It should be more efficient in terms of both run time and memory usage. Using the original benchmark code with size = int(1e7) it might take ~%67 of the time that ncls takes: AIList: CPU times: user 8.07 s, sys: 952 ms, total: 9.02 s; Wall time: 9.04 s; ncls: CPU times: user 11.9 s, sys: 1.27 s, total: 13.2 s; Wall time: 13.5 s; The memory usage is improved as well (no duplication of data).
